### ISSUE TITLE
Auto-select by name?

### ISSUE THREAD

**Issue by Pysis868** [ybrs/assh#1]
Is there a way to automatically select an EC2 instance by name, say, by using a command line option, and if there isn't one already that can be used for this purpose, could it be added?

**Comment by ybrs** [comment]
Sorry for the late reply.

I added this in 54077b2 though not published on PyPI, will be using it for a few days.

you can now give `--filter-tags=Name:app1` or `--filter-name=app1`

the whole command becomes,

`assh --filter-name=app3 projectname ssh`

or for short version

`assh -N=app3 projectname ssh`

also if there is only one result from the aws api - only one server with that tag - we don't show the curses ui and skip to the command, so you don't need to select anything if there is only one server with that name.

please let me know what you think.

thank you,

**Comment by Pysis868** [comment]
Not able to try it yet through upgrading with `pip`, but the use cases seem perfect!

**Comment by ybrs** [comment]
published to pypi so now you can upgrade with pip now. please let me know if you see any issues.

**Comment by Pysis868** [comment]
Updated today via pip to receive `assh-0.1.11.tar.gz`.

I had issued this command: `> assh -r __ --eval 'ssh username@__' "projectName" -N=machineName`, which does bring up my project's machines correctly, but does not select the machine automatically (which is what I was hoping it would do), or enter into the query box at all.

When I issue this command: `> assh -N=machineName -r __ --eval 'ssh username@__' "projectName"`, it gives this error trace:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/assh/assh.py", line 332, in <module>
    assh()
  File "/usr/local/lib/python2.7/site-packages/assh/assh.py", line 322, in assh
    fn = picker.get_cmd_fn(args.command)
  File "/usr/local/lib/python2.7/site-packages/assh/assh.py", line 98, in get_cmd_fn
    fn = getattr(self.settings, 'cmd_%s' % self.args.command.upper(), None)
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by Pysis868** [comment]
Still having the error ;)
